# Generated .workmux.yaml + the single worktree-setup script (design
# D6, agentic-devenv spec, tasks 4.2/4.3).
#
# Defaults are TRAIT-KEYED, not universal:
#   * submodules -> the setup script re-inits them (worktrees don't
#     carry submodule state).
#   * NO stateful devenv services -> `.direnv`/`.devenv` are symlinked
#     from the main worktree to reuse the devenv cache (avoids
#     re-evaluating the flake per worktree). Repos WITH services keep
#     per-worktree state (databases, process dirs) — never shared.
#   * secret-bearing dotfiles (vault-resolved `.env` and friends) are
#     COPIED per worktree, never symlink-shared.
#
# One worktree setup path for all creators: the generated
# `.workmux.yaml` `post_create` and the Claude Code `WorktreeCreate`
# hook (wired via devenv's first-party `claude.code.hooks` in the
# devenv adapter) invoke the SAME script, so the two paths cannot
# drift.
#
# Detect-and-degrade (4.3) lives HERE, outside the shell: the setup
# script probes flake git-discovery BEFORE placing anything; on the
# known worktree-of-a-submodule failure it emits the constraint + the
# `nix shell` workaround and exits without partial artifacts.
# (Re-tested 2026-07-15 under devenv 2.1.2 + Nix 2.34.7: the historical
# init failure no longer reproduces — the probe is a cheap safety net,
# not the expected path.)
{
  lib,
  config,
  ...
}: let
  cfg = config.agentic.workmux;

  setupScript = pkgs:
    pkgs.writeShellApplication {
      name = "agentic-worktree-setup";
      runtimeInputs = [pkgs.git];
      text = ''
        # Degrade check FIRST (before any artifact lands): the known
        # failure mode is nix/devenv unable to resolve the repo under
        # a worktree-of-a-submodule's double gitdir indirection.
        if ! nix flake metadata --json >/dev/null 2>&1; then
          if [ -f .git ] && grep -q '\.git/modules/' .git 2>/dev/null; then
            echo "agentic: nix cannot initialize in this worktree of a SUBMODULE" >&2
            echo "  (gitdir indirection: .git -> parent/.git/modules/<sub>/worktrees/<name>)." >&2
            echo "  Dev-shell tools are unavailable here. Workaround: invoke tools via" >&2
            echo "    nix shell nixpkgs#<tool> --command <tool> ..." >&2
            echo "  Do NOT edit .envrc per-worktree." >&2
            exit 1
          fi
          echo "agentic: nix flake discovery failed in this worktree (not the submodule constraint) — investigate before continuing." >&2
          exit 1
        fi

        main_wt="$(git worktree list --porcelain | head -1 | sed 's/^worktree //')"

        ${lib.optionalString cfg.traits.submodules ''
          # Worktrees don't carry submodule state.
          git submodule update --init
        ''}

        # Per-worktree copies (secret-bearing files are never shared;
        # .envrc/direnv grants are per-directory).
        for f in ${lib.escapeShellArgs (cfg.copyFiles ++ cfg.traits.secretDotfiles)}; do
          if [ ! -e "$f" ] && [ -e "$main_wt/$f" ]; then
            cp -R "$main_wt/$f" "$f"
          fi
        done

        ${lib.optionalString (!cfg.traits.statefulServices) ''
          # Share the devenv/direnv cache with the main worktree —
          # safe only because this repo declares no stateful services.
          [ -e "$main_wt/.direnv" ] && ln -sfn "$main_wt/.direnv" .direnv
          [ -e "$main_wt/.devenv" ] && ln -sfn "$main_wt/.devenv" .devenv
        ''}

        command -v direnv >/dev/null 2>&1 && direnv allow || true
      '';
    };

  yamlBody =
    {
      main_branch = cfg.mainBranch;
      merge_strategy = cfg.mergeStrategy;
      inherit (cfg) mode agent;
      post_create = ["agentic-worktree-setup-placeholder"];
      pre_merge = cfg.preMerge;
      dashboard = cfg.dashboard;
    }
    // lib.optionalAttrs (cfg.autoNameModel != null) {
      auto_name = {
        model = cfg.autoNameModel;
        system_prompt = cfg.autoNamePrompt;
      };
    }
    // cfg.extraConfig;

  configFile = pkgs: let
    body = (pkgs.formats.yaml {}).generate "workmux-body.yaml" (yamlBody
      // {
        post_create = ["${setupScript pkgs}/bin/agentic-worktree-setup"];
      });
    header = pkgs.writeText "workmux-header" ''
      # GENERATED by the agentic devenv module — do not edit; override via
      # `agentic.workmux.*` options. Regenerated on shell entry.
      #
      # Submodule note: git worktrees don't carry submodule state — the
      # setup script re-initializes them (trait-keyed: only when the repo
      # declares submodules).
      # Direnv note: `.direnv`/`.devenv` are symlinked from the main
      # worktree to reuse the devenv cache ONLY when the repo declares no
      # stateful devenv services; secret-bearing dotfiles are copied per
      # worktree, never symlink-shared.
      # pre_merge rationale: deliberately NOT `--all-systems` — that
      # evaluates every host on every arch from the merging workstation
      # (IFD-on-foreign-arch bugs, minutes-to-hours). Full-fleet coverage
      # is CI's job; this hook catches format drift and local-system eval
      # errors only, and MUST pass --accept-flake-config when the flake's
      # nixConfig declares experimental features.
      # Worktree setup: post_create and the Claude Code WorktreeCreate
      # hook invoke the SAME script so the two creation paths cannot
      # drift.
    '';
  in
    pkgs.runCommand "workmux.yaml" {} ''
      cat ${header} ${body} > $out
    '';
in {
  options.agentic.workmux = {
    traits = {
      submodules = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Repo has git submodules (setup script re-inits them per worktree).";
      };
      statefulServices = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Repo runs stateful devenv services (disables .direnv/.devenv sharing across worktrees).";
      };
      secretDotfiles = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        example = [".env"];
        description = "Secret-bearing dotfiles copied per worktree, never symlink-shared.";
      };
    };

    copyFiles = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [".envrc" ".claude"];
      description = "Files copied from the main worktree into each new worktree when absent.";
    };

    mainBranch = lib.mkOption {
      type = lib.types.str;
      default = "main";
    };
    mergeStrategy = lib.mkOption {
      type = lib.types.str;
      default = "rebase";
    };
    mode = lib.mkOption {
      type = lib.types.str;
      default = "window";
      description = ''
        workmux worktree layout: "window" (works with both the herdr
        and tmux backends) or "session" (tmux only — the herdr backend
        rejects session mode outright). Defaults to "window" because the
        fleet drives the herdr backend (workmux input is the herdr fork).
      '';
    };
    agent = lib.mkOption {
      type = lib.types.str;
      default = "claude --permission-mode=auto";
      description = "Agent command a new worktree pane launches.";
    };

    autoNameModel = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Model id for workmux auto_name branch naming (null omits the block; supply a CURRENT model id).";
    };
    autoNamePrompt = lib.mkOption {
      type = lib.types.str;
      default = "Generate a short kebab-case git branch name from the prompt. Use conventional prefixes: fix/, feat/, chore/, refactor/, docs/. Max 50 chars total. Output ONLY the branch name, nothing else.";
      description = "System prompt for auto_name.";
    };

    preMerge = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "nix fmt --accept-flake-config"
        "nix flake check --impure --no-build --accept-flake-config"
      ];
      description = "pre_merge hook commands (see the generated header for the no-all-systems rationale).";
    };

    dashboard = lib.mkOption {
      type = lib.types.attrs;
      default = {
        commit = "/commit";
        merge = "!workmux merge";
        preview_size = 60;
      };
    };

    extraConfig = lib.mkOption {
      type = lib.types.attrs;
      default = {};
      description = "Freeform keys merged last into the generated config (overrides via options, not file edits).";
    };
  };

  options.agentic.workmuxLib = lib.mkOption {
    type = lib.types.raw;
    readOnly = true;
    description = "`configFile pkgs` (the generated .workmux.yaml) and `setupScript pkgs` (the single worktree-setup entrypoint).";
  };

  config.agentic.workmuxLib = {inherit configFile setupScript;};
}
