# Fixture checks for workmux generation + the worktree setup script
# (tasks 4.2/4.3): a submodule repo gets the submodule init; a repo
# with a secret .env (the finance shape) copies .env per worktree.
# Neither shares devenv state, and both give linked worktrees their own
# hooks dir. The degrade diagnostic lives in the setup script BEFORE
# any artifact placement.
{
  inputs,
  config,
  ...
}: {
  perSystem = {
    pkgs,
    system,
    ...
  }: let
    mkFixture = module:
      inputs.flake-parts.lib.mkFlake {inherit inputs;} {
        systems = [system];
        imports = [
          config.flake.flakeModules.default
          module
          ({config, ...}: {
            perSystem = {pkgs, ...}: {
              packages = {
                workmux-config = config.agentic.workmuxLib.configFile pkgs;
                workmux-setup = config.agentic.workmuxLib.setupScript pkgs;
              };
            };
          })
        ];
      };

    submoduleRepo = mkFixture {
      agentic.workmux.traits.submodules = true;
      agentic.workmux.autoNameModel = "fixture-model-1";
    };

    financeShape = mkFixture {
      agentic.workmux.traits.secretDotfiles = [".env"];
    };

    pkgOf = fixture: name: fixture.packages.${system}.${name};
  in {
    checks.workmux =
      pkgs.runCommand "agentic-workmux" {
        nativeBuildInputs = [pkgs.gnugrep];
      } ''
        set -euo pipefail

        cfg=${pkgOf submoduleRepo "workmux-config"}
        setup=${pkgOf submoduleRepo "workmux-setup"}/bin/agentic-worktree-setup

        # Generated header carries the operational rationale.
        grep -qF 'GENERATED by the agentic devenv module' "$cfg"
        grep -qF 'pre_merge rationale' "$cfg"
        grep -qF 'main_branch: main' "$cfg"
        # Default worktree layout is window: the herdr backend (fleet
        # default) rejects session mode outright (#88).
        grep -qF 'mode: window' "$cfg"
        grep -qF 'model: fixture-model-1' "$cfg"
        grep -qF 'nix flake check --impure --no-build --accept-flake-config' "$cfg"
        # post_create invokes the single setup script.
        grep -qF "$setup" "$cfg"

        # Submodule repo: init; per-worktree devenv state and hooks.
        grep -qF 'git submodule update --init' "$setup"
        ! grep -qF '.direnv" .direnv' "$setup"
        ! grep -qF '.devenv" .devenv' "$setup"
        grep -qF 'git config --worktree core.hooksPath "$git_dir/hooks"' "$setup"
        # Dev shell warmed once, outside any agent sandbox.
        grep -qF 'nix develop --impure -c true' "$setup"
        grep -qF 'devenv shell -- true' "$setup"
        # Degrade probe precedes artifact placement and names the
        # constraint + workaround.
        grep -qF 'nix flake metadata --json' "$setup"
        grep -qF 'worktree of a SUBMODULE' "$setup"
        grep -qF 'nix shell nixpkgs#<tool>' "$setup"

        # Finance shape: secret .env copied per worktree, no submodule
        # init, no shared devenv state, per-worktree hooks.
        fsetup=${pkgOf financeShape "workmux-setup"}/bin/agentic-worktree-setup
        ! grep -qF '.direnv" .direnv' "$fsetup"
        grep -qF 'core.hooksPath' "$fsetup"
        ! grep -qF 'git submodule update --init' "$fsetup"
        grep -qF ".env" "$fsetup"

        # No auto_name block without a declared model id.
        fcfg=${pkgOf financeShape "workmux-config"}
        ! grep -qF 'auto_name' "$fcfg"

        touch $out
      '';
  };
}
